"""rename department

Revision ID: 3d8c3e62a7f5
Revises: fed4c0b7ef9e
Create Date: 2024-11-25 22:16:57.924260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d8c3e62a7f5'
down_revision = 'fed4c0b7ef9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###